name: rootfs

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        version: [6.7-working]
    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc-aarch64-linux-gnu bc flex bison kmod bash cpio binutils tar git wget dpkg-dev libssl-dev

      - name: Build kernel
        run: sudo sh nabu-kernel_build.sh ${{ matrix.version }}

      - name: Upload deb packages
        uses: actions/upload-artifact@v4
        with:
          name: xiaomi-nabu-debs_${{ matrix.version }}
          path: ${{ github.workspace }}/*.deb

  rootfs:
    runs-on: ubuntu-24.04
    needs: kernel
    strategy:
      fail-fast: false
      matrix:
        desktop: [ubuntu-desktop, lomiri]
        kernel: [6.7-working]
    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Download deb packages
        uses: actions/download-artifact@v4
        with:
          name: xiaomi-nabu-debs_${{ matrix.kernel }}
          path: xiaomi-nabu-debs_${{ matrix.kernel }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip build-essential gcc-aarch64-linux-gnu bc flex bison kmod bash cpio binutils tar git wget dpkg-dev libssl-dev qemu-user-static binfmt-support
          sudo apt install -y 7zip || sudo apt install -y p7zip-full
          sudo update-binfmts --enable qemu-aarch64 || true

      - name: Build rootfs
        run: sudo sh nabu-rootfs_build.sh ${{ matrix.desktop }} ${{ matrix.kernel }}

      - name: Upload rootfs.7z
        uses: actions/upload-artifact@v4
        with:
          name: rootfs_${{ matrix.desktop }}_${{ matrix.kernel }}
          path: rootfs.7z
          compression-level: 0
